/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UcTooltip {}
}

declare global {


  interface HTMLUcTooltipElement extends Components.UcTooltip, HTMLStencilElement {}
  var HTMLUcTooltipElement: {
    prototype: HTMLUcTooltipElement;
    new (): HTMLUcTooltipElement;
  };
  interface HTMLElementTagNameMap {
    'uc-tooltip': HTMLUcTooltipElement;
  }
}

declare namespace LocalJSX {
  interface UcTooltip {}

  interface IntrinsicElements {
    'uc-tooltip': UcTooltip;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'uc-tooltip': LocalJSX.UcTooltip & JSXBase.HTMLAttributes<HTMLUcTooltipElement>;
    }
  }
}


